# '\' for easier reading
s = "GCAGTCAGTTGTGGTACTGGCCAGCGATGGTGCGGGGTGGGTAGCTCCCGGGAACGCCGT\
     TAAAACCCTTGTTGACTCTGATGAGATAGTTCCTCTTGGTGAGAAGGAACTGGGGAACCT\
     GCTTAATCTACCGTAGTCTCAGAGTAAAGTTTGGTGGCTATGATATGCAGCGTACGATTT\
     CAGACTTTTCTTTTATAAGACGTCCAATGGTGTCTCGCCGACACAGTGGTAATAGGGATGT\
     AAGTATGCCGGCGCGCGATCTGCCACTGCTCGGGGGTACAGTAGCCTATACCCGTGATAG\
     ACGCGAACATCGACGCCTGCAGCTAATCGGAAGTCTCCAACGAAGCCGTGAACAGACAAT\
     ATTCGGGCCGCGTTGACGAGTGCACCGCCATGCTTCGCTCGCAGGTCGAAGGGACTCACA\
     ACCTTCACTCAACTCGCATGATCGGAGACAAAGTGGCCATTTGCGAGAGCGGCACCTCCTG\
     CCCTCCTACCCTAGGCTGCCTCTCGACCAGACCTTACTACTTACCGAGCGAGATAATCAGA\
     GGATTGGCAAGAGTAGTAGATTATTTCTATCACTGTCAGCGGAAGTGATCCCTCCCTGCC\
     CGACGTCTATTGACGGCACCGACAGTTGCAGCCGAGCCCTCGGAACTATCCACAGCTGAG\
     CAATGTACGCGGAGACGAGGTGTCCGACGGTGGACTGCTAGGGCAGGCCAACCCCTAGGC\
     CTCTTCAGAGGACCTCCGCCTCTGGTCGTTGTCTCGCGATTTAGTTAAATTAAGGCATGC\
     CTGCTGCGAAATATTGAAGATAACAACAAATGATGTCTGGTGGGGTGAGGTAGCGCGACT\
     CTAGCCCGGTAGTTTACCAGAACACACGGCTTCCCGGCCGTATATACGGTGAGCCCACTAA\
     GGAGTTCAATTCATAATTAGTTAA"

print(s.count('A'), s.count('C'), s.count('G'), s.count('T'))
